### ISSUE TITLE
Blue Portals item checklist

### ISSUE THREAD

**Issue by Byzarru** [TheDarkBomber/BEE2-items-TheDarkBomber-Contributions#12]
I've never played the game! This list is based on items seen in the walkthroughs and mod page.

# New items #
Some of these items were previously suggested but turned down either due to the limitations of BEE or their practicality.
- [x] Cube catcher [suggested]
- [ ] Fire cube
- [ ] Magnet [suggested]
- [ ] Repulsor
- [ ] Water [declined due to a bug with the robots] [but will be done anyway]
- [ ] Electrified water [suggested]
- [ ] Unfizzlable cube
- [ ] Ice cube
- [ ] Frozen buttons
- [ ] Visible timer
- [ ] Light
- [ ] Eye
- [ ] Mirror
- [ ] Activation Cube
- [ ] Red Flow (one voxel of liquid used for transport)
- [ ] Fan [suggested]
- [x] Breakable Glass [added by Lautaro] [Default Pack]
- [ ] Countdown Timer [confirmed by TeamSpen] [Default Pack]
- [ ] Music Cube [appears in the cut sequel]
- [ ] Light Cube [appears in the Extended Play]
- [ ] Heavy Cube [appears on a wall texture, not in-game]

# Extras #
### BPDC Style ###
* Use Blue Portals textures for P1 items
* Smiley Face textures for antlines and indicators
* Black walls are made of stone in some occasions
- [ ] Style

### Misc ###
- [ ] Stylevar for Blue Portals portal sounds
- [x] Blue Portals music
- [ ] Modify standard Fizzler and Death Fizzler for Fizzle-Proof cubes

**Comment by TheDarkBomber** [comment]
The instances are available on ModDB, and the style will be based off the Portal 1 style. So, yes, this will be done.

**Comment by TheDarkBomber** [comment]
The visible timer will just be the styled timer for the pedestal button in the Blue Portals style.

**Comment by vrad-exe** [comment]
Make sure to configure it so that unstyled items will use their P1 variants.

**Comment by TheDarkBomber** [comment]
They will, it's based off P1 style.

**Comment by Byzarru** [comment]
The glows in BP are white rather than orange, and everything has a yellowish glow to it (I assume that's already an attribute of the items on moddb, but all custom items will need to be adjusted). 

Are there files up for Blue Portals 2 (for the P2 variations of the items) or do they need to be remade?

**Comment by TheDarkBomber** [comment]
Just P1 variations.

**Comment by Luke18033** [comment]
Please merge this into the default pack...

**Comment by vrad-exe** [comment]
Did you just delete my comment?

**Comment by vrad-exe** [comment]
I was trying to tell you to merge it with the default pack, but you just *have* to keep it separate, don't you?

**Comment by Byzarru** [comment]
This is a logical choice (merging with the default pack, there is no precedent otherwise). Some of these items are not only already going into the default pack, but will be requested to be part of it, piece by piece, as well. 

Also, I've made a few notes about how some items should work with other styles (#13). I might be able to make a few custom assets (provided the music cubes are going to be added 🎹 🥁 👏 ).

**Comment by vrad-exe** [comment]
Frozen buttons should just be Start Reversed on the normal button.

**Comment by TheDarkBomber** [comment]
Will be merged with the Default Pack. (see Gitter, unless you've already seen it...)

**Comment by Byzarru** [comment]
Finally found all of the music tracks :p

**Comment by TeamSpen210** [comment]
Unfizzleable cubes would probably need a compiler change to allow them to work - we'd need to filter all the triggers in the map so they aren't fizzled by them. I reckon panels and goo should still destroy it?

**Comment by TheDarkBomber** [comment]
Yes, this can be done by using a model filter on cube fizzling triggers on fizzlers.

**Comment by TeamSpen210** [comment]
I'll add a compiler result which makes the filter and applies it to all fizzler items in the map.

**Comment by TheDarkBomber** [comment]
Ok.

**Comment by Byzarru** [comment]
A note about the stone walls:
I have previously suggested using the cutout wall tiles to make the stone walls. The white portions could generate white accents while the dark portions would just become stone. (Not all of the black walls are stone, that's why I'm suggesting this) Additionally, a 'wall accent' item should be added for the blue accents (which could also have a potential use in TWTM style for the bright areas).

**Comment by vrad-exe** [comment]
Electrified water should be done just by placing an "electrifier" item in water.

**Comment by Byzarru** [comment]
That could potentially be coupled with an electric panel previously suggested on the main repo.

**Comment by vrad-exe** [comment]
> I reckon panels and goo should still destroy it?

@TeamSpen210 - Panels should still destroy it, but for Goo, it shouldn't be destroyed, instead floating to the top. This could make for some interesting puzzles.

Edit: One issue with this - what if a bottomless pit skybox is selected? The cubes wouldn't float which could break puzzles.

**Comment by TheDarkBomber** [comment]
Cube Catcher Deactivated:
 ![catcher-off](https://files.gitter.im/TheDarkBomber/BEE2-items-TheDarkBomber-Contributions/8H6e/thumb/20170219211847_1.jpg)
Cube Catcher Activated:
 ![catcher-on](https://files.gitter.im/TheDarkBomber/BEE2-items-TheDarkBomber-Contributions/iTiz/20170219211903_1.jpg)

**Comment by Byzarru** [comment]
You posted the same picture.

**Comment by TheDarkBomber** [comment]
Fixed!

**Comment by vrad-exe** [comment]
Why is the P1 dropper dropping P2 cubes?

**Comment by TheDarkBomber** [comment]
The Companion Cube is P1, but the Standard Cube isn't.

**Comment by vrad-exe** [comment]
Water would always be electrified and deadly in Co-op.

**Comment by vrad-exe** [comment]
Also, does the Cube Catcher have an embed space?

**Comment by SP2G50000** [comment]
In the cut sequel, the Propulsion Gel was re-skinned to look like oil, would that make it into this style?

**Comment by Byzarru** [comment]
It shouldn't, so as to not confuse players switching between styles.

**Comment by vrad-exe** [comment]
This issue was moved to BEEmod/BEE2-items#2139.
